/*
 * Style library sync + lint.
 *
 * The canvas can point at the host repo's real style sources in
 * canvas.config.json:
 *
 *   "styles": {
 *     "tailwind": "../tailwind.config.js",   // optional — a JS config whose `theme` becomes the tokens
 *     "css": ["../src/style.css"]            // component classes (may use @layer / @apply)
 *   }
 *
 * `syncStyles` pulls those sources and generates, under design-canvas/shared/:
 *   library.gen.js   — runtime injection for prototypes (ds.js loads it):
 *                      tailwind.config tokens + the component CSS as text/tailwindcss
 *   library.gen.css  — a plain copy of the component CSS (for lint + reference)
 *   library.json     — the class inventory + sync metadata (the viewer feeds it
 *                      to the Claude prompt so generated screens stay on-library)
 *
 * `lintStyles` scans every prototype for styling that doesn't belong:
 *   inline <style> rules, style="" attributes, rules duplicating a library
 *   class, invented library-look-alike classes, and the same custom style
 *   repeated across screens (a candidate for the library).
 */
import { promises as fs } from 'node:fs';
import fss from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const readJSON = async (file, fallback) => {
  try { return JSON.parse(await fs.readFile(file, 'utf8')); } catch { return fallback; }
};
const writeIfChanged = async (file, content) => {
  const prev = fss.existsSync(file) ? await fs.readFile(file, 'utf8') : null;
  if (prev === content) return 'unchanged';
  await fs.writeFile(file, content);
  return prev === null ? 'created' : 'updated';
};

// Normalize a declaration block to a comparable key.
const normDecls = (s) =>
  String(s || '').split(';').map((d) => d.trim().replace(/\s+/g, ' ')).filter(Boolean).sort().join('; ');

// Flat rule list from CSS. Nested wrappers (@layer/@media headers) never match
// because a selector can't contain braces — only innermost rules are captured.
export function parseRules(css) {
  const out = [];
  const clean = String(css || '').replace(/\/\*[\s\S]*?\*\//g, '');
  const re = /([^{}]+)\{([^{}]*)\}/g;
  let m;
  while ((m = re.exec(clean))) {
    const selector = m[1].trim().replace(/\s+/g, ' ');
    if (!selector || selector.startsWith('@')) continue;
    out.push({ selector, decls: normDecls(m[2]) });
  }
  return out;
}

const classesInSelector = (sel) => [...String(sel).matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)].map((m) => m[1]);

// JS-escape guard so generated document.write strings can't close their own tag.
const jsStr = (s) => JSON.stringify(s).replace(/<\//g, '<\\/');

export async function loadStylesConfig(canvasRoot) {
  const cfg = await readJSON(path.join(canvasRoot, 'canvas.config.json'), {});
  return cfg.styles || null;
}

export async function syncStyles(canvasRoot) {
  const cfg = await loadStylesConfig(canvasRoot);
  if (!cfg) throw new Error('No "styles" block in canvas.config.json — add {"styles": {"tailwind": "...", "css": ["..."]}} pointing at your repo\'s style sources.');

  const sources = [];
  let theme = null;
  let themeError = null;
  if (cfg.tailwind) {
    const file = path.resolve(canvasRoot, cfg.tailwind);
    sources.push(cfg.tailwind);
    try {
      const mod = await import(pathToFileURL(file).href + '?t=' + Date.now());
      const tw = mod.default || mod;
      theme = JSON.parse(JSON.stringify(tw.theme || {}));   // drops functions/plugins
    } catch (e) {
      themeError = `could not load ${cfg.tailwind}: ${e.message}`;
    }
  }

  let css = '';
  for (const rel of cfg.css || []) {
    const file = path.resolve(canvasRoot, rel);
    sources.push(rel);
    css += `/* ---- from ${rel} ---- */\n` + (await fs.readFile(file, 'utf8')) + '\n';
  }
  // Build-time directives the runtime CDN can't process.
  const stripped = [];
  css = css.replace(/^\s*@(tailwind|import)\b[^;\n]*;?\s*$/gm, (m) => { stripped.push(m.trim()); return ''; });

  const rules = parseRules(css);
  const classes = [...new Set(rules.flatMap((r) => classesInSelector(r.selector)))].sort();

  const twMode = !!theme || /@apply|@layer/.test(css);
  const syncedAt = new Date().toISOString();
  const lines = [
    '// GENERATED by `easel styles sync` — do not edit; re-run the sync to refresh.',
    `// sources: ${sources.join(', ')} · synced ${syncedAt}`,
  ];
  if (theme) lines.push(`document.write(${jsStr('<script>tailwind.config=' + JSON.stringify({ theme }) + '</script>')});`);
  lines.push(`document.write(${jsStr(`<style${twMode ? ' type="text/tailwindcss"' : ''}>` + css + '</style>')});`);

  const shared = path.join(canvasRoot, 'shared');
  await fs.mkdir(shared, { recursive: true });
  const files = {};
  files['shared/library.gen.js'] = await writeIfChanged(path.join(shared, 'library.gen.js'), lines.join('\n') + '\n');
  files['shared/library.gen.css'] = await writeIfChanged(path.join(shared, 'library.gen.css'),
    `/* GENERATED by \`easel styles sync\` from: ${sources.join(', ')} · ${syncedAt} */\n` + css);
  files['shared/library.json'] = await writeIfChanged(path.join(shared, 'library.json'),
    JSON.stringify({ syncedAt, sources, tailwind: !!theme, themeError, stripped, classes }, null, 2) + '\n');

  return { sources, tailwind: !!theme, themeError, classes, stripped, files };
}

// Tailwind utility namespaces that must never count as "library look-alike" prefixes.
const TW_NAMESPACES = new Set([
  'table', 'text', 'bg', 'border', 'flex', 'grid', 'font', 'leading', 'rounded', 'shadow', 'inline',
  'block', 'items', 'justify', 'gap', 'w', 'h', 'p', 'm', 'px', 'py', 'pt', 'pb', 'pl', 'pr', 'mx',
  'my', 'mt', 'mb', 'ml', 'mr', 'cursor', 'outline', 'from', 'via', 'to', 'min', 'max', 'space',
  'divide', 'ring', 'transition', 'duration', 'hover', 'focus', 'placeholder', 'overflow', 'absolute',
  'relative', 'fixed', 'sticky', 'top', 'bottom', 'left', 'right', 'z', 'col', 'row', 'order',
  'object', 'opacity', 'underline', 'uppercase', 'lowercase', 'capitalize', 'truncate', 'whitespace',
  'break', 'align', 'list', 'appearance', 'select', 'resize', 'tracking', 'antialiased', 'container',
  'sr', 'not', 'group', 'peer', 'self', 'content', 'basis', 'grow', 'shrink', 'aspect', 'columns',
  'decoration', 'indent', 'scroll', 'snap', 'touch', 'will', 'fill', 'stroke', 'accent', 'caret',
  'pointer', 'invisible', 'visible', 'static', 'isolate', 'float', 'clear', 'box', 'hidden',
]);

export async function lintStyles(canvasRoot) {
  const lib = await readJSON(path.join(canvasRoot, 'shared', 'library.json'), null);
  const libCssFile = path.join(canvasRoot, 'shared', 'library.gen.css');
  if (!lib || !fss.existsSync(libCssFile)) {
    throw new Error('No synced library found — run `easel styles sync` first.');
  }
  const libClasses = new Set(lib.classes || []);
  const prefixes = [...new Set([...libClasses].map((c) => c.split('-')[0]))].filter((p) => p && !TW_NAMESPACES.has(p));
  const libByDecl = new Map();
  for (const r of parseRules(await fs.readFile(libCssFile, 'utf8'))) {
    if (r.decls) libByDecl.set(r.decls, (libByDecl.get(r.decls) || []).concat(r.selector));
  }

  const findings = [];
  const crossMap = new Map();   // declKey -> [{view, where}]
  const modulesDir = path.join(canvasRoot, 'modules');
  const views = [];
  if (fss.existsSync(modulesDir)) {
    for (const mod of (await fs.readdir(modulesDir, { withFileTypes: true })).filter((d) => d.isDirectory())) {
      for (const v of (await fs.readdir(path.join(modulesDir, mod.name), { withFileTypes: true })).filter((d) => d.isDirectory())) {
        if (fss.existsSync(path.join(modulesDir, mod.name, v.name, 'index.html'))) views.push(`${mod.name}/${v.name}`);
      }
    }
  }

  for (const view of views) {
    const html = await fs.readFile(path.join(modulesDir, view, 'index.html'), 'utf8');

    // inline <style> blocks
    let inlineRules = 0;
    for (const block of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)) {
      for (const r of parseRules(block[1])) {
        inlineRules++;
        if (r.decls && libByDecl.has(r.decls)) {
          findings.push({ type: 'duplicate-of-library', view, selector: r.selector, duplicates: libByDecl.get(r.decls).join(', ') });
        } else if (r.decls) {
          crossMap.set(r.decls, (crossMap.get(r.decls) || []).concat({ view, where: r.selector }));
        }
      }
    }
    if (inlineRules) findings.push({ type: 'inline-styles', view, rules: inlineRules });

    // style="" attributes
    const attrs = [...html.matchAll(/style=(["'])([\s\S]*?)\1/g)].map((m) => normDecls(m[2])).filter(Boolean);
    if (attrs.length) {
      findings.push({ type: 'style-attributes', view, count: attrs.length, examples: [...new Set(attrs)].slice(0, 3) });
      for (const a of attrs) crossMap.set(a, (crossMap.get(a) || []).concat({ view, where: 'style=""' }));
    }

    // invented library-look-alike classes
    const used = new Set([...html.matchAll(/class=(["'])([\s\S]*?)\1/g)].flatMap((m) => m[2].split(/\s+/)).filter(Boolean));
    for (const c of used) {
      if (libClasses.has(c)) continue;
      if (prefixes.some((p) => c === p || c.startsWith(p + '-'))) {
        findings.push({ type: 'library-lookalike', view, class: c });
      }
    }
  }

  // the same custom style in several screens = a candidate for the library
  for (const [decls, where] of crossMap) {
    const viewsHit = [...new Set(where.map((w) => w.view))];
    if (viewsHit.length >= 2) findings.push({ type: 'repeated-custom-style', decls, views: viewsHit });
  }

  const summary = {};
  for (const f of findings) summary[f.type] = (summary[f.type] || 0) + 1;
  const report = { generatedAt: new Date().toISOString(), library: { syncedAt: lib.syncedAt, classes: lib.classes.length }, summary, findings };
  await fs.writeFile(path.join(canvasRoot, 'style-report.json'), JSON.stringify(report, null, 2) + '\n');
  return report;
}
